#!/bin/sh

#read fuses to files 'low' and 'high':
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U lfuse:r:low:r
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U hfuse:r:high:r




#write fuses:
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U lfuse:w:0xe2:m
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U hfuse:w:0xd4:m # preserve EEPROM; BOD=4.5V
#sleep 1

avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -e -U flash:w:batterytest.hex:i
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U eeprom:w:batterytest.eep

