#!/bin/sh

avrdude -p m16 -c stk500 -P /dev/ttyUSB0 -e -U flash:w:master.hex:i
avrdude -p m16 -c stk500 -P /dev/ttyUSB0 -U eeprom:w:master.eep
avrdude -p m16 -c stk500 -P /dev/ttyUSB0 -U lfuse:w:0x3f:m
avrdude -p m16 -c stk500 -P /dev/ttyUSB0 -U hfuse:w:0xc1:m
#avrdude -p m16 -c stk500 -P /dev/ttyUSB0 -U lock:w:0x3c:m

